apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: hloc-fourseasons
  name: hloc-fourseasons
spec:
  template:
    metadata:
      labels:
        app: hloc-fourseasons
    spec:
      restartPolicy: "Never"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: gpu-type
      #           operator: NotIn
      #           values:
      #             - K40
      containers:
      - name: hloc-fourseasons
        command: ["/bin/bash", "-c"]
        args: 
          # anything we forgot
          - apt-get install -y rsync &&
            cp -R /root/data/datasets/4Seasons /app/datasets/4Seasons &&
            unzip recording_2020-04-07_10-20-32.zip -d reference &&
            unzip recording_2020-03-24_17-36-22.zip -d training &&
            unzip recording_2020-03-03_12-03-23.zip -d validation &&
            unzip recording_2020-03-24_17-45-31.zip -d test0 &&
            unzip recording_2020-04-23_19-37-00.zip -d test1 &&
            cd /app && source sourceme.sh &&
            python3 pipelines/initialize_datasets.py --base_dir datasets --outputs /root/local_data/output --dataset 4Seasons &&
            python3 run_pipeline.py datasets /root/local_data/output r2d2 4Seasons &&
            rsync -a /root/local_data/output/ /root/data/output/
        resources:
          limits:
            cpu: "8"
            memory: "20Gi"
            nvidia.com/gpu: 1
            ephemeral-storage: 100Gi
          requests:
            cpu: "8"
            memory: "20Gi"
            nvidia.com/gpu: 1
            ephemeral-storage: 100Gi
        image: gitlab-registry.nautilus.optiputer.net/vivecenter-berkeley-edu/hloc:latest
        volumeMounts:
        - mountPath: /root/data
          name: fs-store
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: fs-store
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            clusterNamespace: rook
            fsName: nautilusfs
            path: /half-potato
            mountUser: half-potato
            mountSecret: ceph-fs-secret
      imagePullSecrets:
      - name: regcredlp # this is the secret for you credentials to pull a private image



